[menu]
gfile = "filemenu"

[[menuitem]]
command = "PREVFILECONF"
hotkey = "{"

[[menuitem]]
command = "NEXTFILECONF"
hotkey = "}"

[[menuitem]]
command = "PREVFILEAREA"
hotkey = "["

[[menuitem]]
command = "NEXTFILEAREA"
hotkey = "]"

[[menuitem]]
command = "FILECONFS"
hotkey = "J"

[[menuitem]]
command = "FILEAREAS"
hotkey = "A"

[[menuitem]]
command = "LISTFILES"
hotkey = "L"

[[menuitem]]
command = "DOWNLOAD"
hotkey = "D"

[[menuitem]]
command = "UPLOAD"
hotkey = "U"

[[menuitem]]
command = "CLEARTAGGED"
hotkey = "C"

[[menuitem]]
command = "NEWFILES"
hotkey = "N"

[[menuitem]]
command = "FILESEARCH"
hotkey = "S"

[[menuitem]]
command = "PREVMENU"
hotkey = "Q"

[[menuitem]]
command = "SUBMENU"
data = "logoff"
hotkey = "G"
