[menu]
gfile = "gopher"

[[menuitem]]
command = "PHLOGRECENT"
hotkey = "R"

[[menuitem]]
command = "PHLOGNEW"
hotkey = "E"

[[menuitem]]
command = "PHLOGMANAGE"
hotkey = "M"

[[menuitem]]
command = "PREVMENU"
hotkey = "Q"

[[menuitem]]
command = "SUBMENU"
data = "logoff"
hotkey = "G"
