[menu]
gfile = "logoff"

[[menuitem]]
command = "GOODBYE"
hotkey = "Y"

[[menuitem]]
command = "PREVMENU"
hotkey = "N"

[[menuitem]]
command = "FEEDBACK"
hotkey = "F"

[[menuitem]]
command = "RUNSCRIPT"
data = "automessage"
hotkey = "L"