[menu]
gfile = "mainmenu"

[[menuitem]]
command = "SUBMENU"
hotkey = "M"
data = "message"

[[menuitem]]
command = "SUBMENU"
hotkey = "D"
data = "doors"

[[menuitem]]
command = "SUBMENU"
hotkey = "T"
data = "file"

[[menuitem]]
command = "LAST10"
hotkey = "1"

[[menuitem]]
command = "SYSINFO"
hotkey = "I"

[[menuitem]]
command = "SETTINGS"
hotkey = "S"

[[menuitem]]
command = "FEEDBACK"
hotkey = "F"

[[menuitem]]
command = "LISTUSERS"
hotkey = "L"

[[menuitem]]
command = "NODEMSG"
hotkey = "N"

[[menuitem]]
command = "BULLETINS"
hotkey = "B"

[[menuitem]]
command = "RUNSCRIPT"
hotkey = "R"
data = "rumors"

[[menuitem]]
command = "RUNSCRIPT"
hotkey = "O"
data = "oneliners"

[[menuitem]]
command = "SUBMENU"
hotkey = "G"
data = "logoff"
