[menu]
gfile = "mainmenu"

[[menuitem]]
command = "SUBMENU"
hotkey = "M"
data = "message"

[[menuitem]]
command = "SUBMENU"
hotkey = "D"
data = "doors"

[[menuitem]]
command = "LAST10"
hotkey = "1"

[[menuitem]]
command = "SUBMENU"
hotkey = "G"
data = "logoff"
