[menu]
gfile = "messagemenu"

[[menuitem]]
command = "LISTCONFS"
hotkey = "J"

[[menuitem]]
command = "LISTAREAS"
hotkey = "A"

[[menuitem]]
command = "LISTMSGS"
hotkey = "L"

[[menuitem]]
command = "POSTMSG"
hotkey = "P"

[[menuitem]]
command = "MAILSCAN"
hotkey = "N"

[[menuitem]]
command = "PREVMENU"
hotkey = "Q"

[[menuitem]]
command = "SUBMENU"
data = "logoff"
hotkey = "G"
