cmake_minimum_required (VERSION 3.0)
project (talisman)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_MODULE_PATH ${talisman_SOURCE_DIR}/../cmake/)
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -Wall -ggdb")
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -Wall")
find_package(SQLITE3 REQUIRED)
find_package(OpenSSL REQUIRED)
find_package(Lua 5.3 REQUIRED)
find_package(LibSSH REQUIRED)
find_package(ICONV REQUIRED)
add_executable(talisman main.cpp Node.cpp Config.cpp User.cpp Menu.cpp MsgArea.cpp MsgConf.cpp ../Common/Squish.cpp CallLog.cpp Door.cpp Settings.cpp ../Common/Logger.cpp Editor.cpp Email.cpp Protocol.cpp Bulletins.cpp FileConf.cpp FileArea.cpp Archiver.cpp Script.cpp SshClient.cpp Nodelist.cpp FullScreenEditor.cpp AnsiEditor.cpp Phlog.cpp IndexReader.cpp Strings.cpp Rlogin.cpp Telnet.cpp)
include_directories(${SQLITE3_INCLUDE_DIRS} ${OPENSSL_INCLUDE_DIR} ${LIBSSH_INCLUDE_DIR} ${LUA_INCLUDE_DIR} ${ICONV_INCLUDE_DIR} ../Common )
if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
	target_link_libraries (talisman ${SQLITE3_LIBRARIES} ${CMAKE_THREAD_LIBS_INIT} ${OPENSSL_CRYPTO_LIBRARY} ${LIBSSH_LIBRARIES} ${LUA_LIBRARIES} ${ICONV_LIBRARIES} util pthread)
else()
	if (CMAKE_SYSTEM_NAME MATCHES "Haiku")
		target_link_libraries (talisman ${SQLITE3_LIBRARIES} ${CMAKE_THREAD_LIBS_INIT} ${OPENSSL_CRYPTO_LIBRARY} ${LIBSSH_LIBRARIES} ${LUA_LIBRARIES} ${ICONV_LIBRARIES}  stdc++fs pthread network bsd)	
	else()
	        target_link_libraries (talisman ${SQLITE3_LIBRARIES} ${CMAKE_THREAD_LIBS_INIT} ${OPENSSL_CRYPTO_LIBRARY} ${LIBSSH_LIBRARIES} ${LUA_LIBRARIES} ${ICONV_LIBRARIES} stdc++fs util pthread)
	endif()
endif()

