; Script generated by the Inno Script Studio Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Talisman BBS"
#define MyAppVersion "0.4"
#define MyAppPublisher "Andrew Pamment"
#define MyAppURL "https://talismanbbs.com/"
#define MyAppExeName "Servo.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{7B0968D1-22AF-4B04-B3DF-8352C74331D4}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=C:\bbs\
DefaultGroupName={#MyAppName}
OutputBaseFilename=Talisman-v{#MyAppVersion}-Setup
Compression=lzma
SolidCompression=yes
LicenseFile=..\..\LICENSE

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\apamm\source\repos\Talisman\Release\Servo.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\apamm\source\repos\Talisman\Release\Talisman.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\apamm\source\repos\Talisman\Release\Toolbelt.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\apamm\source\repos\Talisman\Talisman\gfiles\*"; DestDir: "{app}\gfiles\"; Flags: onlyifdoesntexist
Source: "C:\Users\apamm\source\repos\Talisman\Talisman\menus\*"; DestDir: "{app}\menus\"; Flags: onlyifdoesntexist
Source: "C:\Users\apamm\source\repos\Talisman\Talisman\scripts\*"; DestDir: "{app}\scripts"; Flags: onlyifdoesntexist
Source: "C:\Users\apamm\source\repos\Talisman\Talisman\data\trashcan.txt"; DestDir: "{app}\data"; Flags: onlyifdoesntexist
Source: "C:\Users\apamm\source\repos\Talisman\Talisman\data\bulletins.toml"; DestDir: "{app}\data"; Flags: onlyifdoesntexist
Source: "C:\Users\apamm\source\repos\Talisman\Talisman\data\msgconfs.toml"; DestDir: "{app}\data"; Flags: onlyifdoesntexist
Source: "C:\Users\apamm\source\repos\Talisman\Talisman\data\mb_local.toml"; DestDir: "{app}\data"; Flags: onlyifdoesntexist
Source: "C:\Users\apamm\source\repos\Talisman\Talisman\data\fileconfs.toml"; DestDir: "{app}\data"; Flags: onlyifdoesntexist
Source: "C:\Users\apamm\source\repos\Talisman\Talisman\data\fb_general.toml"; DestDir: "{app}\data"; Flags: onlyifdoesntexist
Source: "C:\Users\apamm\source\repos\Talisman\Talisman\data\seclevels.toml"; DestDir: "{app}\data"; Flags: onlyifdoesntexist
Source: "C:\Users\apamm\source\repos\Talisman\Talisman\data\loginitems.toml"; DestDir: "{app}\data"; Flags: onlyifdoesntexist
Source: "C:\Users\apamm\source\repos\Talisman\Talisman\win32_deps\*.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\apamm\source\repos\Talisman\Talisman\win32_deps\*.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\apamm\source\repos\Talisman\Talisman\win32_deps\protocols.toml"; DestDir: "{app}\data"; Flags: onlyifdoesntexist
Source: "C:\Users\apamm\source\repos\Talisman\Talisman\win32_deps\archivers.toml"; DestDir: "{app}\data"; Flags: onlyifdoesntexist
Source: "C:\Program Files (x86)\OpenSSL-Win32\bin\libcrypto-1_1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\apamm\source\repos\Talisman\Talisman\win32_deps\talisman.ini"; DestDir: "{app}"; Flags: onlyifdoesntexist
Source: "C:\Users\apamm\source\repos\Talisman\Talisman\win32_deps\talisman.ini"; DestDir: "{app}\dist"; Flags: ignoreversion
Source: "C:\Users\apamm\source\repos\Talisman\Talisman\gfiles\*"; DestDir: "{app}\dist\gfiles\"; Flags: ignoreversion
Source: "C:\Users\apamm\source\repos\Talisman\Talisman\menus\*"; DestDir: "{app}\dist\menus\"; Flags: ignoreversion
Source: "C:\Users\apamm\source\repos\Talisman\Talisman\scripts\*"; DestDir: "{app}\dist\scripts"; Flags: ignoreversion
Source: "C:\Users\apamm\source\repos\Talisman\Talisman\data\trashcan.txt"; DestDir: "{app}\dist\data"; Flags: ignoreversion
Source: "C:\Users\apamm\source\repos\Talisman\Talisman\data\bulletins.toml"; DestDir: "{app}\dist\data"; Flags: ignoreversion
Source: "C:\Users\apamm\source\repos\Talisman\Talisman\data\msgconfs.toml"; DestDir: "{app}\dist\data"; Flags: ignoreversion
Source: "C:\Users\apamm\source\repos\Talisman\Talisman\data\mb_local.toml"; DestDir: "{app}\dist\data"; Flags: ignoreversion
Source: "C:\Users\apamm\source\repos\Talisman\Talisman\data\fileconfs.toml"; DestDir: "{app}\dist\data"; Flags: ignoreversion
Source: "C:\Users\apamm\source\repos\Talisman\Talisman\data\fb_general.toml"; DestDir: "{app}\dist\data"; Flags: ignoreversion
Source: "C:\Users\apamm\source\repos\Talisman\Talisman\data\seclevels.toml"; DestDir: "{app}\dist\data"; Flags: ignoreversion
Source: "C:\Users\apamm\source\repos\Talisman\Talisman\data\loginitems.toml"; DestDir: "{app}\dist\data"; Flags: ignoreversion
Source: "C:\Users\apamm\source\repos\Talisman\Talisman\win32_deps\protocols.toml"; DestDir: "{app}\dist\data"; Flags: ignoreversion
Source: "C:\Users\apamm\source\repos\Talisman\Talisman\win32_deps\archivers.toml"; DestDir: "{app}\dist\data"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Dirs]
Name: "{app}\data"
Name: "{app}\temp"
Name: "{app}\logs"
Name: "{app}\gfiles"
Name: "{app}\menus"
Name: "{app}\msgs"
Name: "{app}\scripts\"
Name: "{app}\scripts\data"
Name: "{app}\dloads"
Name: "{app}\dloads\general"
Name: "{app}\dloads\general\uploads"
Name: "{app}\dloads\general\misc"
Name: "{app}\dist"
Name: "{app}\dist\gfiles"
Name: "{app}\dist\data"
Name: "{app}\dist\menus"
Name: "{app}\dist\scripts"


[Icons]
Name: "{group}\{#MyAppName} (Servo)"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{#MyAppName} (Documentation)"; Filename: "https://talismanbbs.com/docs/"
Name: "{commondesktop}\{#MyAppName} (Servo)"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{commondesktop}\{#MyAppName} (Documentation)"; Filename: "https://talismanbbs.com/docs/"; Tasks: desktopicon

[Code]
var
  BBSDetailsPage: TInputQueryWizardPage;
  BBSName : string;
  SysopName : string;
  LocationStr : string;
  QwkIdStr : string;
  InstallPath : string;
  UpgradeBool : Boolean;
function FileReplaceString(const FileName, SearchString, ReplaceString: string):boolean;
var
  MyFile : TStrings;
  MyText : string;
begin
  MyFile := TStringList.Create;

  try
    result := true;

    try
      MyFile.LoadFromFile(FileName);
      MyText := MyFile.Text;

      { Only save if text has been changed. }
      if StringChangeEx(MyText, SearchString, ReplaceString, True) > 0 then
      begin;
        MyFile.Text := MyText;
        MyFile.SaveToFile(FileName);
      end;
    except
      result := false;
    end;
  finally
    MyFile.Free;
  end;
end;

function GetUninstallString: string;
var
  sUnInstPath: string;
  sUnInstallString: String;
begin
  Result := '';
  sUnInstPath := ExpandConstant('Software\Microsoft\Windows\CurrentVersion\Uninstall\{{7B0968D1-22AF-4B04-B3DF-8352C74331D4}_is1'); { Your App GUID/ID }
  sUnInstallString := '';
  if not RegQueryStringValue(HKLM, sUnInstPath, 'UninstallString', sUnInstallString) then
    RegQueryStringValue(HKCU, sUnInstPath, 'UninstallString', sUnInstallString);
  Result := sUnInstallString;
end;

function IsUpgrade: Boolean;
begin
  Result := (GetUninstallString() <> '');
end;

procedure InitializeWizard;
begin
  if IsUpgrade() = false then
  begin;
    BBSDetailsPage := CreateInputQueryPage(wpWelcome,
      'BBS Details', 'Tell me about your BBS...',
      'Please specify your BBS Details, ' +
      'then click Next.');
    BBSDetailsPage.Add('BBS Name', false); 
    BBSDetailsPage.Add('Sysop Username', false);
    BBSDetailsPage.Add('Location', false);
    BBSDetailsPage.Add('QWK ID', false);
    UpgradeBool := false;
  end else
  begin;
    UpgradeBool := true;
  end;
end;
procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
  begin;
    if UpgradeBool = false then
    begin;
      BBSName := BBSDetailsPage.Values[0];
      SysopName := BBSDetailsPage.Values[1];
      LocationStr := BBSDetailsPage.Values[2];
      QwkIdStr := Copy(Uppercase(BBSDetailsPage.Values[3]), 0, 8);

      InstallPath := ExpandConstant('{app}');
             
      StringChangeEx(InstallPath, '\', '\\', True)

      FileReplaceString(ExpandConstant('{app}\talisman.ini'), '__BBS_NAME__', BBSName);
      FileReplaceString(ExpandConstant('{app}\talisman.ini'), '__SYSOP_NAME__', SysopName);
      FileReplaceString(ExpandConstant('{app}\talisman.ini'), '__LOCATION__', LocationStr);
      FileReplaceString(ExpandConstant('{app}\talisman.ini'), '__QWK_ID__', QwkIdStr);
      FileReplaceString(ExpandConstant('{app}\data\protocols.toml'), '__INST_PATH__', InstallPath);
      FileReplaceString(ExpandConstant('{app}\data\archivers.toml'), '__INST_PATH__', InstallPath);
      FileReplaceString(ExpandConstant('{app}\dist\talisman.ini'), '__BBS_NAME__', BBSName);
      FileReplaceString(ExpandConstant('{app}\dist\talisman.ini'), '__SYSOP_NAME__', SysopName);
      FileReplaceString(ExpandConstant('{app}\dist\talisman.ini'), '__LOCATION__', LocationStr);
      FileReplaceString(ExpandConstant('{app}\dist\talisman.ini'), '__QWK_ID__', QwkIdStr);
      FileReplaceString(ExpandConstant('{app}\dist\data\protocols.toml'), '__INST_PATH__', InstallPath);
      FileReplaceString(ExpandConstant('{app}\dist\data\archivers.toml'), '__INST_PATH__', InstallPath);
    end;
  end;
end;
