cmake_minimum_required (VERSION 2.6)
project (postie)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_MODULE_PATH ${postie_SOURCE_DIR}/../cmake/)
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -Wall -ggdb -std=c++17")
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -Wall -std=c++17")
find_package(SQLite3 REQUIRED)
add_executable(postie main.cpp Archiver.cpp Config.cpp Logger.cpp Scanner.cpp Squish.cpp Tosser.cpp Dupe.cpp TicProc.cpp)
include_directories(${SQLITE3_INCLUDE_DIRS})
if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
	target_link_libraries (postie ${SQLITE3_LIBRARIES})
else()
	target_link_libraries (postie ${SQLITE3_LIBRARIES} -lstdc++fs)
endif()

